### ISSUE TITLE
Request: Example of how to use Appium Tizen TV driver on a Samsung TV

### ISSUE THREAD

**Issue by Chanak7** [headspinio/appium-tizen-tv-driver#118]
Hi team,

How are you all? Hope everyone is doing well.  

Firstly, thank you for creating this fantastic repo. I was looking at the driver documentation and got lost! 

Please provide an example of how one can implement it in a real scenario. I am familiar with appium for mobile devices, but I want to implement this on a Samsung TV. 

A couple of questions about the driver:

1. After installation, can we inspect the TV's elements? For instance, can we view the app ID and buttons if it is a browser app on the TV?
2. Or is it only meant to be used as a replacement for the TV remote?

**Comment by jlipps** [comment]
Unfortunately there aren't very many good open source demo apps so a real world example is probably not doable right now.

> After installation, can we inspect the TV's elements?

Yes, use the page source command

> For instance, can we view the app ID and buttons if it is a browser app on the TV?

It depends on what type of app it is. This driver only supports web-based apps. It also only supports apps that you own. You can't automate apps that you didn't develop.

> Or is it only meant to be used as a replacement for the TV remote?

No, it's a full automation driver, with the restrictions mentioned. But you can also use it as a remote.
