### ISSUE TITLE
[OS] Windows: Unable to locate tizen binary file

### ISSUE THREAD

**Issue by Chanak7** [headspinio/appium-tizen-tv-driver#119]
Hi team,

Can you please help me to resolve the issue listed below:

**Used development platform details**:

| OS|      Version     |  
|----------|:-------------:|
| Windows 10|   21H2 (Build 19044.2130)| 

**Steps to Reproduce**

1. In windows, set **TIZEN_HOME** as an environment variable  —I used (**C:\tizen-studio**)
2. Setup main.js with the desired capabilities and run main.js using node

**Actual result:**
1. Gives an error, listed below:

```node
C:\Users\ckk\Downloads\appiumWithJS\node_modules\appium-tizen-tv-driver\lib\cli\helpers.js:69
    throw new Error(
          ^
Error: Tried to find binary at C:\tizen-studio\tools\ide\bin\tizen but it did not exist or was not executable. Please double-check permissions and TIZEN_HOME value
```
**Expected result:**
1. Runs the command without errors

**Notes:**
1. We tried this on macOS and it works there
2. On Windows we have a **tizen.bat** file but on macOS we only have **tizen** file

**Main.js code:**
```js
// Import Tizen driver
const tizendio = require("appium-tizen-tv-driver");

async function main() {
  // Create an instance of the TizenTV driver
  const client = new tizendio.TizenTVDriver();

  // Create session

  await client.createSession({
    // Add desired capabilites
    firstMatch: [
      {
        platformName: "TizenTV",
        "appium:automationName": "TizenTV",
        "appium:deviceName": "10.0.0.43:26101",

        // Set chrome driver
        "appium:chromedriverExecutable":
          "C:\\Users\\ckk\\Downloads\\appiumWithJS\\chromedriver.exe",

        // Path to the web app we are trying to install
        "appium:app": "C:\\Users\\ckk\\Downloads\\HTML5.wgt",
        "appium:appPackage": "1",
        "appium:noReset": true,
      },
    ],
  });
}

main();
```

**Comment by jlipps** [comment]
So on Windows the file is `C:\tizen-studio\tools\ide\bin\tizen.bat`?

**Comment by Chanak7** [comment]
Yes, that is correct
