### ISSUE TITLE
Unable to update the existing drivers neither able to install any new drivers due to the below error in tizen TV drivers

### ISSUE THREAD

**Issue by rajasubudhi1988** [headspinio/appium-tizen-tv-driver#150]
**I am not able to install any new drivers or not able to update any drivers which are installed earlier in the mac.
Not sure why i see error dependents to Chromedriver and Tizen TV driver.**

@jlipps @boneskull
Please refer the logs below.

**Comment by rajasubudhi1988** [comment]
raja.subudhi@YFYTXJ24VR ~ % appium driver list
WARN Appium Appium encountered 11 warnings while validating drivers found in manifest /Users/raja.subudhi/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "YouiEngine" has 1 potential problem: 
WARN Appium   - Driver "YouiEngine" (package `appium-youiengine-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.46) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-youiengine-driver` to add a peer dependency on `^appium@2.0.0-beta.46`.
✔ Listing available drivers
- tizentv@0.7.3 [installed (NPM)]
- xcuitest@4.12.2 [installed (NPM)]
- uiautomator2@2.10.2 [installed (NPM)]
- espresso@2.13.5 [installed (NPM)]
- mac2@1.4.5 [installed (NPM)]
- windows@2.1.2 [installed (NPM)]
- gecko@1.1.3 [installed (NPM)]
- safari@3.2.4 [installed (NPM)]
- YouiEngine@1.2.9 [installed (NPM)]
- flutter@1.9.1 [installed (NPM)]
- webos@0.0.2 [installed (NPM)]
- youiengine [not installed]
- mac [not installed]
- tizen [not installed]
raja.subudhi@YFYTXJ24VR ~ % appium driver list --updates
WARN Appium Appium encountered 11 warnings while validating drivers found in manifest /Users/raja.subudhi/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "YouiEngine" has 1 potential problem: 
WARN Appium   - Driver "YouiEngine" (package `appium-youiengine-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.46) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-youiengine-driver` to add a peer dependency on `^appium@2.0.0-beta.46`.
✔ Listing available drivers
- tizentv@0.7.3 [installed (NPM)] [Up to date]
- xcuitest@4.12.2 [installed (NPM)] [4.12.3 available]
- uiautomator2@2.10.2 [installed (NPM)] [Up to date]
- espresso@2.13.5 [installed (NPM)] [Up to date]
- mac2@1.4.5 [installed (NPM)] [Up to date]
- windows@2.1.2 [installed (NPM)] [Up to date]
- gecko@1.1.3 [installed (NPM)] [Up to date]
- safari@3.2.4 [installed (NPM)] [Up to date]
- YouiEngine@1.2.9 [installed (NPM)] [Up to date]
- flutter@1.9.1 [installed (NPM)] [1.10.0 available]
- webos@0.0.2 [installed (NPM)] [Up to date]
- youiengine [not installed]
- mac [not installed]
- tizen [not installed]
raja.subudhi@YFYTXJ24VR ~ % appium driver update installed
WARN Appium Appium encountered 11 warnings while validating drivers found in manifest /Users/raja.subudhi/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "YouiEngine" has 1 potential problem: 
WARN Appium   - Driver "YouiEngine" (package `appium-youiengine-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.46) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-youiengine-driver` to add a peer dependency on `^appium@2.0.0-beta.46`.
✔ Checking if driver 'tizentv' is updatable
✖ Checking if driver 'tizentv' needs an update
✔ Checking if driver 'xcuitest' is updatable
✔ Checking if driver 'xcuitest' needs an update
✖ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver@4.12.3'
✖ Updating driver 'xcuitest' from 4.12.2 to 4.12.3
✔ Checking if driver 'uiautomator2' is updatable
✖ Checking if driver 'uiautomator2' needs an update
✔ Checking if driver 'espresso' is updatable
✖ Checking if driver 'espresso' needs an update
✔ Checking if driver 'mac2' is updatable
✖ Checking if driver 'mac2' needs an update
✔ Checking if driver 'windows' is updatable
✖ Checking if driver 'windows' needs an update
✔ Checking if driver 'gecko' is updatable
✖ Checking if driver 'gecko' needs an update
✔ Checking if driver 'safari' is updatable
✖ Checking if driver 'safari' needs an update
✔ Checking if driver 'YouiEngine' is updatable
✖ Checking if driver 'YouiEngine' needs an update
✔ Checking if driver 'flutter' is updatable
✔ Checking if driver 'flutter' needs an update
✖ Installing 'flutter' using NPM install spec 'appium-flutter-driver@1.10.0'
✖ Updating driver 'flutter' from 1.9.1 to 1.10.0
✔ Checking if driver 'webos' is updatable
✖ Checking if driver 'webos' needs an update
ℹ Update report:
ℹ   - 'tizentv' had no updates available
✖   - 'xcuitest' failed to update: Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-xcuitest-driver@4.12.3 --json' failed with code 1.

STDOUT:


STDERR:
npm WARN deprecated @types/puppeteer@7.0.4: This is a stub types definition. puppeteer provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @dabh/colors@1.4.0: @dabh/colors has been renamed to @colors/colors. Please update your package.json.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver
npm ERR! command failed
npm ERR! command sh -c -- node install-npm.js
npm ERR! [21:43:29] Error installing Chromedriver: Cannot find module '@appium/support'
npm ERR! Require stack:
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium/support.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR! [21:43:29] Error: Cannot find module '@appium/support'
npm ERR! Require stack:
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium/support.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:841:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium/support.js:13:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/lib/install.js:1:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR! [21:43:29] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "sh -c -- node install-npm.js\n[21:43:29] Error installing Chromedriver: Cannot find module '@appium/support'\nRequire stack:\n- /Users/raja.subudhi/.appium/node_modules/appium/support.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js\n[21:43:29] Error: Cannot find module '@appium/support'\nRequire stack:\n- /Users/raja.subudhi/.appium/node_modules/appium/support.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n    at Function.Module._load (node:internal/modules/cjs/loader:841:27)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium/support.js:13:18)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/lib/install.js:1:1)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n[21:43:29] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raja.subudhi/.npm/_logs/2022-11-26T16_11_56_351Z-debug-0.log
ℹ   - 'uiautomator2' had no updates available
ℹ   - 'espresso' had no updates available
ℹ   - 'mac2' had no updates available
ℹ   - 'windows' had no updates available
ℹ   - 'gecko' had no updates available
ℹ   - 'safari' had no updates available
ℹ   - 'YouiEngine' had no updates available
✖   - 'flutter' failed to update: Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-flutter-driver@1.10.0 --json' failed with code 1.

STDOUT:


STDERR:
npm WARN deprecated @types/puppeteer@7.0.4: This is a stub types definition. puppeteer provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated @dabh/colors@1.4.0: @dabh/colors has been renamed to @colors/colors. Please update your package.json.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver
npm ERR! command failed
npm ERR! command sh -c -- node install-npm.js
npm ERR! [21:43:58] Error installing Chromedriver: Cannot find module '@appium/support'
npm ERR! Require stack:
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium/support.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR! [21:43:58] Error: Cannot find module '@appium/support'
npm ERR! Require stack:
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium/support.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:841:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium/support.js:13:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/lib/install.js:1:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR! [21:43:58] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "sh -c -- node install-npm.js\n[21:43:58] Error installing Chromedriver: Cannot find module '@appium/support'\nRequire stack:\n- /Users/raja.subudhi/.appium/node_modules/appium/support.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js\n[21:43:58] Error: Cannot find module '@appium/support'\nRequire stack:\n- /Users/raja.subudhi/.appium/node_modules/appium/support.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n    at Function.Module._load (node:internal/modules/cjs/loader:841:27)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium/support.js:13:18)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/lib/install.js:1:1)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n[21:43:58] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raja.subudhi/.npm/_logs/2022-11-26T16_13_40_070Z-debug-0.log
ℹ   - 'webos' had no updates available
raja.subudhi@YFYTXJ24VR ~ %

**Comment by rajasubudhi1988** [comment]
2022-11-26T16_13_40_070Z-debug-0.log

**Comment by rajasubudhi1988** [comment]
[2022-11-26T16_13_40_070Z-debug-0.log](https://github.com/headspinio/appium-tizen-tv-driver/files/10096626/2022-11-26T16_13_40_070Z-debug-0.log)

**Comment by rajasubudhi1988** [comment]
[KazuCocoa](https://github.com/KazuCocoa)
@jlipps @boneskull  any update in this?

**Comment by rajasubudhi1988** [comment]
raja.subudhi@YFYTXJ24VR ~ % appium driver install --source=npm @headspinio/appium-roku-driver                                                                                                               
WARN Appium Appium encountered 11 warnings while validating drivers found in manifest /Users/raja.subudhi/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "YouiEngine" has 1 potential problem: 
WARN Appium   - Driver "YouiEngine" (package `appium-youiengine-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.46) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-youiengine-driver` to add a peer dependency on `^appium@2.0.0-beta.46`.
✖ Installing '@headspinio/appium-roku-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock @headspinio/appium-roku-driver --json' failed with code 1.

STDOUT:


STDERR:
npm WARN deprecated @types/puppeteer@7.0.4: This is a stub types definition. puppeteer provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @dabh/colors@1.4.0: @dabh/colors has been renamed to @colors/colors. Please update your package.json.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver
npm ERR! command failed
npm ERR! command sh -c -- node install-npm.js
npm ERR! [21:35:29] Error installing Chromedriver: Cannot find module '@appium/support'
npm ERR! Require stack:
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium/support.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR! [21:35:29] Error: Cannot find module '@appium/support'
npm ERR! Require stack:
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium/support.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:841:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium/support.js:13:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/lib/install.js:1:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR! [21:35:29] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "sh -c -- node install-npm.js\n[21:35:29] Error installing Chromedriver: Cannot find module '@appium/support'\nRequire stack:\n- /Users/raja.subudhi/.appium/node_modules/appium/support.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js\n[21:35:29] Error: Cannot find module '@appium/support'\nRequire stack:\n- /Users/raja.subudhi/.appium/node_modules/appium/support.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n    at Function.Module._load (node:internal/modules/cjs/loader:841:27)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium/support.js:13:18)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/lib/install.js:1:1)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n[21:35:29] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raja.subudhi/.npm/_logs/2022-11-27T16_03_37_970Z-debug-0.log
raja.subudhi@YFYTXJ24VR ~ %

**Comment by rajasubudhi1988** [comment]
@KazuCocoa 
From clean up ./Users/raja.subudhi/.appium i seen the error almost all the time.
Once i uninstalled Tizen driver all thing works well,I am able to install and update other drivers.
Kindly suggest what ll be the root cause and resolve this issue.

also i see error 
"sh -c -- node install-npm.js\n[21:35:29] Error installing Chromedriver: Cannot find module
npm ERR! [21:35:29] Error: Cannot find module '@appium/support'

**Comment by jlipps** [comment]
@rajasubudhi1988 please provide more information such as output logs. start from a clean install and show what is the issue.
