### ISSUE TITLE
Error in starting appium session onTizen OS

### ISSUE THREAD

**Issue by Varadekushagra** [headspinio/appium-tizen-tv-driver#302]
I am trying to execute the following code

const wdio = require("webdriverio");

const opts = {
    // path: '/wd/hub',
    port: 4723,
    capabilities: {
        "platformName": "TizenTV",
        "appium:automationName" : "TizenTV",
        "appium:deviceName" : "172.31.42.205:26101",
        "appium:chromedriverExecutable" : "/Users/kushagravarade/Downloads/chromedriver",
        "appium:rcToken" : "16085789",
        "appium:appPackage" : "org.tizen.example.MovieLibrary"
    }
  };
  
  async function main () {
    const client = await wdio.remote(opts);
    console.log("I got client as: " , client)
    // await client.deleteSession();
  }
  
  main();
  
and I am getting the error when running the code. I am attaching error log and also appium log. Can you please help me with this issue.

[appium.log](https://github.com/headspinio/appium-tizen-tv-driver/files/10907018/appium.log)  
[err.log](https://github.com/headspinio/appium-tizen-tv-driver/files/10907017/err.log)

**Comment by jlipps** [comment]
something seems wrong in how you have started the server or the session. if you include the full appium log i may be able to see what
