### ISSUE TITLE
sdb shell 0 debug fails on TizenTV 2017

### ISSUE THREAD

**Issue by Jiyvn** [headspinio/appium-tizen-tv-driver#584]
#### Problem
command `sdb shell 0 debug` works on Tizen 5.5 (TizenTV 2020) but fails for Tizen 3.0 (TizenTV 2017)  with same wgt
2020
<img width="812" alt="image" src="https://github.com/headspinio/appium-tizen-tv-driver/assets/73217816/b1608c2e-c435-4c2f-bbc9-31d252b9e753">
2017
<img width="812" alt="image" src="https://github.com/headspinio/appium-tizen-tv-driver/assets/73217816/c9a6c92c-69dd-4dc5-95f3-23e230755866">

sdb capability
<img width="1624" alt="image" src="https://github.com/headspinio/appium-tizen-tv-driver/assets/73217816/b7ec83dc-a780-43d1-bfbe-21cb6e10b3ba">

the install/uninstall command is fine. Is it possible to skip debug command

appium server log
> [38;5;16m[AppiumDriver@60fb][0m Appium v2.5.1 creating new TizenTVDriver (v0.10.0) session
[38;5;16m[AppiumDriver@60fb][0m Checking BaseDriver versions for Appium and TizenTVDriver
[38;5;16m[AppiumDriver@60fb][0m Appium's BaseDriver version is 9.5.2
[38;5;16m[AppiumDriver@60fb][0m TizenTVDriver's BaseDriver version is 8.7.3
[38;5;16m[AppiumDriver@60fb][0m Explicitly enabling use of insecure features:
[38;5;16m[AppiumDriver@60fb][0m     chromedriver_autodownload
[38;5;32m[TizenTVDriver@e01f][0m Creating session with W3C capabilities: {
[38;5;32m[TizenTVDriver@e01f][0m   "alwaysMatch": {
[38;5;32m[TizenTVDriver@e01f][0m     "platformName": "TizenTV",
[38;5;32m[TizenTVDriver@e01f][0m     "appium:deviceAddress": "192.168.10.181:26101",
[38;5;32m[TizenTVDriver@e01f][0m     "appium:udid": "192.168.10.181:26101",
[38;5;32m[TizenTVDriver@e01f][0m     "appium:automationName": "TizenTV",
[38;5;32m[TizenTVDriver@e01f][0m     "appium:rcMode": "remote",
[38;5;32m[TizenTVDriver@e01f][0m     "appium:chromedriverExecutableDir": "/Users/jiyvn/aviu/apps/tv/chromedriver/",
[38;5;32m[TizenTVDriver@e01f][0m     "appium:appPackage": "TXSXgdzhCp.Viu",
[38;5;32m[TizenTVDriver@e01f][0m     "appium:deviceName": "Tizen3.0 2020",
[38;5;32m[TizenTVDriver@e01f][0m     "appium:noReset": false,
[38;5;32m[TizenTVDriver@e01f][0m     "appium:app": "/Users/jiyvn/aviu/apps/Viu_dev.wgt",
[38;5;32m[TizenTVDriver@e01f][0m     "appium:rcToken": "15773870"
[38;5;32m[TizenTVDriver@e01f][0m   },
[38;5;32m[TizenTVDriver@e01f][0m   "firstMatch": [
[38;5;32m[TizenTVDriver@e01f][0m     {}
[38;5;32m[TizenTVDriver@e01f][0m   ]
[38;5;32m[TizenTVDriver@e01f][0m }
[38;5;32m[TizenTVDriver@e01f (012ab4c6)][0m Session created with session id: 012ab4c6-e55d-43d7-b6fe-ddd7de58928f
[38;5;48m[TizenTVDriver][0m Received rcKeypressCooldown of type undefined
[38;5;48m[TizenTVDriver][0m Uninstalling tizen app 'TXSXgdzhCp.Viu' on device '192.168.10.181:26101'
[38;5;48m[TizenTVDriver][0m Running command: /Users/jiyvn/tizen-studio/tools/ide/bin/tizen uninstall -p TXSXgdzhCp.Viu -s 192.168.10.181:26101
[38;5;48m[TizenTVDriver][0m Installing tizen app '/Users/jiyvn/aviu/apps/Viu_dev.wgt' on device '192.168.10.181:26101'
[38;5;48m[TizenTVDriver][0m Running command: /Users/jiyvn/tizen-studio/tools/ide/bin/tizen install -n /Users/jiyvn/aviu/apps/Viu_dev.wgt -s 192.168.10.181:26101
[38;5;48m[TizenTVDriver][0m Listing apps installed on '192.168.10.181:26101'
[38;5;48m[TizenTVDriver][0m Running command: /Users/jiyvn/tizen-studio/tools/sdb -s 192.168.10.181:26101 shell 0 applist
[38;5;48m[TizenTVDriver][0m There are 152 apps installed
[38;5;48m[TizenTVDriver][0m Starting TXSXgdzhCp.Viu in debug mode on 192.168.10.181:26101
[38;5;48m[TizenTVDriver][0m Running command: /Users/jiyvn/tizen-studio/tools/sdb -s 192.168.10.181:26101 shell 0 debug TXSXgdzhCp.Viu
[38;5;48m[TizenTVDriver][0m Cleaning up any ports which have been forwarded
[38;5;16m[AppiumDriver@60fb][0m Event 'newSessionStarted' logged at 1710915243869 (14:14:03 GMT+0800 (China Standard Time))
[38;5;16m[AppiumDriver@60fb][0m Encountered internal error running command: Command '/Users/jiyvn/tizen-studio/tools/sdb -s 192.168.10.181\:26101 shell 0 debug TXSXgdzhCp.Viu' exited with code 1. Stdout was: ''. Stderr was: 'closed '
[38;5;16m[AppiumDriver@60fb][0m Error: Command '/Users/jiyvn/tizen-studio/tools/sdb -s 192.168.10.181\:26101 shell 0 debug TXSXgdzhCp.Viu' exited with code 1
[38;5;16m[AppiumDriver@60fb][0m     at ChildProcess.<anonymous> (/Users/jiyvn/.appium/node_modules/appium-tizen-tv-driver/node_modules/teen_process/lib/exec.js:128:19)
[38;5;16m[AppiumDriver@60fb][0m     at ChildProcess.emit (node:events:518:28)
[38;5;16m[AppiumDriver@60fb][0m     at maybeClose (node:internal/child_process:1105:16)
[38;5;16m[AppiumDriver@60fb][0m     at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
[38;5;0m[HTTP][0m [37m<-- POST /session [39m[31m500[39m [90m15122 ms - 876[39m
[38;5;0m[HTTP][0m [90m[39m

the app should be debuggable as using the same wgt
https://github.com/headspinio/appium-tizen-tv-driver/blob/main/packages/appium-tizen-tv-driver/README.md#troubleshooting 

A similar issue was reported before in repo Samsung/appium-tizen-driver, so that's why I report here
https://github.com/Samsung/appium-tizen-driver/issues/10

**Comment by KazuCocoa** [comment]
`appium:rcOnly` caps would help. Then it skips https://github.com/headspinio/appium-tizen-tv-driver/blob/8abdede79baab1a1382b8e7c91c385bc23a99066/packages/appium-tizen-tv-driver/lib/driver.js#L326

**Comment by Jiyvn** [comment]
thank you @KazuCocoa. Unfortunately, our app is web-based
<img width="1014" alt="image" src="https://github.com/headspinio/appium-tizen-tv-driver/assets/73217816/ea3aa38f-4d8f-49eb-ae4b-28d882351dc1">

**Comment by KazuCocoa** [comment]
Then, so far, it looks like the debug command is used to get debug port by the test target to attach to a chromedriver session. Perhaps... if we have a way to detect a method to get the app's debug port somehow, it will be able to skip.
For example `useOpenDebugPort` capability is it. If you already know the debug port on the tv device, it will let you skip the debug command
